@server=http://localhost:4004
@username=alice
@password=


### GMCHeaderMax
# @name GMCHeaderMax_GET
GET {{server}}/odata/v4/max-key/GMCHeaderMax
Authorization: Basic {{username}}:{{password}}


### GMCHeaderMax
# @name GMCHeaderMax_POST
POST {{server}}/odata/v4/max-key/GMCHeaderMax
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### GMCHeaderMax
# @name GMCHeaderMax_PATCH
PATCH {{server}}/odata/v4/max-key/GMCHeaderMax/undefined
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### GMCHeaderMax
# @name GMCHeaderMax_DELETE
DELETE {{server}}/odata/v4/max-key/GMCHeaderMax/undefined
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
