@server=http://localhost:4004
@username=alice
@password=


### userMaster
# @name userMaster_GET
GET {{server}}/odata/v4/user-master/userMaster
Authorization: Basic {{username}}:{{password}}


### userMaster
# @name userMaster_POST
POST {{server}}/odata/v4/user-master/userMaster
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "10796021-9aae-41eb-881f-6ce9068b48b1",
  "UserName": "UserName-10796021",
  "Password": "Password-10796021",
  "IsAdmin": false
}


### userMaster
# @name userMaster_PATCH
PATCH {{server}}/odata/v4/user-master/userMaster/10796021-9aae-41eb-881f-6ce9068b48b1
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "10796021-9aae-41eb-881f-6ce9068b48b1",
  "UserName": "UserName-10796021",
  "Password": "Password-10796021",
  "IsAdmin": false
}


### userMaster
# @name userMaster_DELETE
DELETE {{server}}/odata/v4/user-master/userMaster/10796021-9aae-41eb-881f-6ce9068b48b1
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
